### ISSUE TITLE
BetterNether Incompatability 

### ISSUE THREAD

**Issue by Imbion** [Xires87/SwordParry#2]
There's an incompatibility issue with the BetterNether mod that causes the Jungle Skeleton (a mob) to crash the game. I origionaly submitted this [issue](https://github.com/quiqueck/BetterNether/issues/113) to the BetterNether github, and then I was refered to report the crash here.

I also created a new instance with just the two mods and their preqs (as well as MixinTrace) to verfiy the issue. Here's the crashlog from that:
```
---- Minecraft Crash Report ----
// You should try our sister game, Minceraft!

Time: 2023-02-13 09:07:54
Description: Rendering entity in world

java.lang.ClassCastException: class org.betterx.betternether.entity.EntityJungleSkeleton cannot be cast to class net.minecraft.class_1657 (org.betterx.betternether.entity.EntityJungleSkeleton is in unnamed module of loader net.fabricmc.loader.impl.launch.knot.KnotClassLoader @27efef64)
	at net.fryc.frycparry.FrycParryClient.lambda$onInitializeClient$0(FrycParryClient.java:15)
	at net.minecraft.class_6395.call(class_6395.java:14)
	at net.minecraft.class_806.method_3495(class_806.java:80)
	at net.minecraft.class_918.method_4019(class_918.java:259)
	at net.minecraft.class_918.method_23177(class_918.java:272)
	at net.minecraft.class_759.method_3233(class_759.java:163)
	at net.minecraft.class_989.method_4192(class_989.java:64)
	at net.minecraft.class_989.method_17162(class_989.java:42)
	at net.minecraft.class_989.method_4199(class_989.java:15)
	at net.minecraft.class_922.method_4054(class_922.java:145)
	at net.minecraft.class_927.method_4072(class_927.java:45)
	at net.minecraft.class_927.method_3936(class_927.java:18)
	at net.minecraft.class_898.method_3954(class_898.java:141)
	at net.minecraft.class_761.method_22977(class_761.java:1568)
	at net.minecraft.class_761.method_22710(class_761.java:1316)
	at net.minecraft.class_757.method_3188(class_757.java:1039)
	at net.minecraft.class_757.method_3192(class_757.java:816)
	at net.minecraft.class_310.method_1523(class_310.java:1177)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:214)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:249)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fryc.frycparry.FrycParryClient.lambda$onInitializeClient$0(FrycParryClient.java:15)
	at net.minecraft.class_6395.call(class_6395.java:14)
	at net.minecraft.class_806.method_3495(class_806.java:80)
	at net.minecraft.class_918.method_4019(class_918.java:259)
	at net.minecraft.class_918.method_23177(class_918.java:272)
	at net.minecraft.class_759.method_3233(class_759.java:163)
	at net.minecraft.class_989.method_4192(class_989.java:64)
	at net.minecraft.class_989.method_17162(class_989.java:42)
	at net.minecraft.class_989.method_4199(class_989.java:15)
	at net.minecraft.class_922.method_4054(class_922.java:145)
	at net.minecraft.class_927.method_4072(class_927.java:45)
	at net.minecraft.class_927.method_3936(class_927.java:18)
	at net.minecraft.class_898.method_3954(class_898.java:141)
	at net.minecraft.class_761.method_22977(class_761.java:1568)
	at net.minecraft.class_761.method_22710(class_761.java:1316)
	at net.minecraft.class_757.method_3188(class_757.java:1039)
Mixins in Stacktrace:
	net.minecraft.class_918:
		net.fabricmc.fabric.mixin.resource.loader.client.KeyedResourceReloadListenerClientMixin (fabric-resource-loader-v0.client.mixins.json)
		net.fabricmc.fabric.mixin.client.indigo.renderer.ItemRendererMixin (fabric-renderer-indigo.mixins.json)
	net.minecraft.class_759:
		net.fabricmc.fabric.mixin.item.client.HeldItemRendererMixin (fabric-item-api-v1.client.mixins.json)
	net.minecraft.class_922:
		net.fabricmc.fabric.mixin.client.rendering.LivingEntityRendererAccessor (fabric-rendering-v1.mixins.json)
	net.minecraft.class_761:
		net.fabricmc.fabric.mixin.client.rendering.WorldRendererMixin (fabric-rendering-v1.mixins.json)
		net.fabricmc.fabric.mixin.resource.loader.client.KeyedResourceReloadListenerClientMixin (fabric-resource-loader-v0.client.mixins.json)
	net.minecraft.class_757:
		net.fabricmc.fabric.mixin.screen.GameRendererMixin (fabric-screen-api-v1.mixins.json)

-- Entity being rendered --
Details:
	Entity Type: betternether:jungle_skeleton (org.betterx.betternether.entity.EntityJungleSkeleton)
	Entity ID: 767
	Entity Name: Jungle Skeleton
	Entity's Exact location: -310.50, 71.00, 43.50
	Entity's Block location: World: (-311,71,43), Section: (at 9,7,11 in -20,4,2; chunk contains blocks -320,-64,32 to -305,319,47), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Entity's Momentum: 0.00, 0.00, 0.00
	Entity's Passengers: []
	Entity's Vehicle: null
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:141)
	at net.minecraft.class_761.method_22977(class_761.java:1568)
	at net.minecraft.class_761.method_22710(class_761.java:1316)
	at net.minecraft.class_757.method_3188(class_757.java:1039)
	at net.minecraft.class_757.method_3192(class_757.java:816)
	at net.minecraft.class_310.method_1523(class_310.java:1177)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:214)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:249)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Mixins in Stacktrace:
	net.minecraft.class_761:
		net.fabricmc.fabric.mixin.client.rendering.WorldRendererMixin (fabric-rendering-v1.mixins.json)
		net.fabricmc.fabric.mixin.resource.loader.client.KeyedResourceReloadListenerClientMixin (fabric-resource-loader-v0.client.mixins.json)
	net.minecraft.class_757:
		net.fabricmc.fabric.mixin.screen.GameRendererMixin (fabric-screen-api-v1.mixins.json)
	net.minecraft.class_310:
		net.fabricmc.fabric.mixin.networking.client.accessor.MinecraftClientAccessor (fabric-networking-api-v1.client.mixins.json)
		org.betterx.betternether.mixin.client.MinecraftClientMixin (betternether.mixins.client.json)
		org.betterx.bclib.mixin.client.MinecraftMixin (bclib.mixins.client.json)
		net.fabricmc.fabric.mixin.datagen.client.MinecraftClientMixin (fabric-data-generation-api-v1.client.mixins.json)
		net.fabricmc.fabric.mixin.screen.MinecraftClientMixin (fabric-screen-api-v1.mixins.json)
		net.fabricmc.fabric.mixin.event.interaction.client.MinecraftClientMixin (fabric-events-interaction-v0.client.mixins.json)
		net.fabricmc.fabric.mixin.event.lifecycle.client.MinecraftClientMixin (fabric-lifecycle-events-v1.client.mixins.json)
		net.fabricmc.fabric.mixin.registry.sync.client.MinecraftClientMixin (fabric-registry-sync-v0.client.mixins.json)

-- Renderer details --
Details:
	Assigned renderer: org.betterx.betternether.entity.render.RenderJungleSkeleton@3aecea7a
	Location: -0.94,-1.62,-2.57 - World: (-1,-2,-3), Section: (at 15,14,13 in -1,-1,-1; chunk contains blocks -16,-64,-16 to -1,319,-1), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Rotation: -95.625
	Delta: 0.51998
Stacktrace:
	at net.minecraft.class_898.method_3954(class_898.java:141)
	at net.minecraft.class_761.method_22977(class_761.java:1568)
	at net.minecraft.class_761.method_22710(class_761.java:1316)
	at net.minecraft.class_757.method_3188(class_757.java:1039)
	at net.minecraft.class_757.method_3192(class_757.java:816)
	at net.minecraft.class_310.method_1523(class_310.java:1177)
	at net.minecraft.class_310.method_1514(class_310.java:768)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:214)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:249)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Mixins in Stacktrace:
	net.minecraft.class_761:
		net.fabricmc.fabric.mixin.client.rendering.WorldRendererMixin (fabric-rendering-v1.mixins.json)
		net.fabricmc.fabric.mixin.resource.loader.client.KeyedResourceReloadListenerClientMixin (fabric-resource-loader-v0.client.mixins.json)
	net.minecraft.class_757:
		net.fabricmc.fabric.mixin.screen.GameRendererMixin (fabric-screen-api-v1.mixins.json)
	net.minecraft.class_310:
		net.fabricmc.fabric.mixin.networking.client.accessor.MinecraftClientAccessor (fabric-networking-api-v1.client.mixins.json)
		org.betterx.betternether.mixin.client.MinecraftClientMixin (betternether.mixins.client.json)
		org.betterx.bclib.mixin.client.MinecraftMixin (bclib.mixins.client.json)
		net.fabricmc.fabric.mixin.datagen.client.MinecraftClientMixin (fabric-data-generation-api-v1.client.mixins.json)
		net.fabricmc.fabric.mixin.screen.MinecraftClientMixin (fabric-screen-api-v1.mixins.json)
		net.fabricmc.fabric.mixin.event.interaction.client.MinecraftClientMixin (fabric-events-interaction-v0.client.mixins.json)
		net.fabricmc.fabric.mixin.event.lifecycle.client.MinecraftClientMixin (fabric-lifecycle-events-v1.client.mixins.json)
		net.fabricmc.fabric.mixin.registry.sync.client.MinecraftClientMixin (fabric-registry-sync-v0.client.mixins.json)

-- Affected level --
Details:
	All players: 1 total; [class_746['Imbion'/71, l='ClientLevel', x=-309.59, y=71.00, z=46.14]]
	Chunk stats: 961, 572
	Level dimension: minecraft:overworld
	Level spawn location: World: (-304,71,32), Section: (at 0,7,0 in -19,4,2; chunk contains blocks -304,-64,32 to -289,319,47), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,-64,0 to -1,319,511)
	Level time: 314 game time, 314 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2341)
	at net.minecraft.class_310.method_1514(class_310.java:787)
	at net.minecraft.client.main.Main.method_44604(Main.java:244)
	at net.minecraft.client.main.Main.main(Main.java:51)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:214)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:249)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Mixins in Stacktrace:
	net.minecraft.class_638:
		net.fabricmc.fabric.mixin.event.lifecycle.client.ClientWorldMixin (fabric-lifecycle-events-v1.client.mixins.json)
	net.minecraft.class_310:
		net.fabricmc.fabric.mixin.networking.client.accessor.MinecraftClientAccessor (fabric-networking-api-v1.client.mixins.json)
		org.betterx.betternether.mixin.client.MinecraftClientMixin (betternether.mixins.client.json)
		org.betterx.bclib.mixin.client.MinecraftMixin (bclib.mixins.client.json)
		net.fabricmc.fabric.mixin.datagen.client.MinecraftClientMixin (fabric-data-generation-api-v1.client.mixins.json)
		net.fabricmc.fabric.mixin.screen.MinecraftClientMixin (fabric-screen-api-v1.mixins.json)
		net.fabricmc.fabric.mixin.event.interaction.client.MinecraftClientMixin (fabric-events-interaction-v0.client.mixins.json)
		net.fabricmc.fabric.mixin.event.lifecycle.client.MinecraftClientMixin (fabric-lifecycle-events-v1.client.mixins.json)
		net.fabricmc.fabric.mixin.registry.sync.client.MinecraftClientMixin (fabric-registry-sync-v0.client.mixins.json)

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: Default, Fabric Mods

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.2, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode, sharing), Oracle Corporation
	Memory: 1359446608 bytes (1296 MiB) / 3063939072 bytes (2922 MiB) up to 4294967296 bytes (4096 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 1600 Six-Core Processor            
	Identifier: AuthenticAMD Family 23 Model 1 Stepping 1
	Microarchitecture: Zen
	Frequency (GHz): 3.49
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce GTX 760
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1187
	Graphics card #0 versionInfo: DriverVersion=30.0.14.7381
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 21693.57
	Virtual memory used (MB): 16455.61
	Swap memory total (MB): 5376.00
	Swap memory used (MB): 310.16
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx4096m
	Fabric Mods: 
		bclib: BCLib 2.1.6
		betternether: Better Nether 7.1.3
		cloth-config: Cloth Config v8 8.2.88
			cloth-basic-math: cloth-basic-math 0.6.1
		fabric-api: Fabric API 0.73.2+1.19.2
			fabric-api-base: Fabric API Base 0.4.15+8f4e8eb390
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.14+93d8cb8290
			fabric-biome-api-v1: Fabric Biome API (v1) 9.1.0+82db024a90
			fabric-block-api-v1: Fabric Block API (v1) 1.0.2+e415d50e90
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.24+c6af733c90
			fabric-client-tags-api-v1: Fabric Client Tags 1.0.5+b35fea8390
			fabric-command-api-v1: Fabric Command API (v1) 1.2.16+f71b366f90
			fabric-command-api-v2: Fabric Command API (v2) 2.2.1+413cbbc790
			fabric-commands-v0: Fabric Commands (v0) 0.2.33+df3654b390
			fabric-containers-v0: Fabric Containers (v0) 0.1.41+df3654b390
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.5.1+7c6cd14d90
			fabric-convention-tags-v1: Fabric Convention Tags 1.2.2+27265b3490
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.8+aeb40ebe90
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.3.7+413cbbc790
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.35+0d0f210290
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.5.4+9244241690
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.34+562bff6e90
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.35+df3654b390
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.24+b6b6abb490
			fabric-item-api-v1: Fabric Item API (v1) 1.6.5+dce4603e90
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.38+9244241690
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.25+5c4fce2890
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.23+df3654b390
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.2.4+1b46dc7890
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.12+83a8659290
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.15+9e7660c690
			fabric-message-api-v1: Fabric Message API (v1) 5.0.7+93d8cb8290
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.23+33fbc73890
			fabric-models-v0: Fabric Models (v0) 0.3.21+c6af733c90
			fabric-networking-api-v1: Fabric Networking API (v1) 1.2.11+10eb22f490
			fabric-networking-v0: Fabric Networking (v0) 0.3.28+df3654b390
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.2.1+d8ef690890
			fabric-particles-v1: Fabric Particles (v1) 1.0.14+4d0d570390
			fabric-recipe-api-v1: Fabric Recipe API (v1) 1.0.1+413cbbc790
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.32+9244241690
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.2.1+2e5408b590
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.7.1+2e5408b590
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.24+df3654b390
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.19+6e0787e690
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.11+4d0d570390
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.27+df3654b390
			fabric-rendering-v1: Fabric Rendering (v1) 1.12.1+d8ef690890
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.1.2+aae9039d90
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.8.3+251d254a90
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.32+4d0d570390
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.3.7+1cc24b1b90
			fabric-sound-api-v1: Fabric Sound API (v1) 1.0.2+c4f28df590
			fabric-textures-v0: Fabric Textures (v0) 1.0.24+aeb40ebe90
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.1.6+413cbbc790
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.3.3+08b73de490
		fabricloader: Fabric Loader 0.14.14
		frycparry: Sword Parry 1.1.1+1.19.2
		java: Java HotSpot(TM) 64-Bit Server VM 17
		minecraft: Minecraft 1.19.2
		mixintrace: MixinTrace 1.1.1+1.17
	Launched Version: 1.19.2
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce GTX 760/PCIe/SSE2 GL version 3.2.0 NVIDIA 473.81, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: Fabric Mods
	Current Language: English (US)
	CPU: 12x AMD Ryzen 5 1600 Six-Core Processor 
	Server Running: true
	Player Count: 1 / 8; [class_3222['Imbion'/71, l='ServerLevel[New World]', x=-309.59, y=71.00, z=46.14]]
	Data Packs: vanilla, Fabric Mods
	World Generation: Experimental
```

**Comment by Xires87** [comment]
Looks like it's not compatibility issue, but a bug in my mod. Whenever skeleton (or other mob) picks up a shield, minecraft goes to sleep.
Jungle skeleton from BetterNether has a chance to spawn with shield so thats why it happens only on better nether biomes.

Thanks for opening this issue, fix is coming.
